# Generated by Django 4.0.4 on 2022-04-17 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminder_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharereminder',
            name='editor',
        ),
        migrations.AlterField(
            model_name='editor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='editor',
        ),
        migrations.AddField(
            model_name='reminder',
            name='editor',
            field=models.ManyToManyField(to='reminder_service.editor'),
        ),
    ]
